-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 14:51:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db-java-intermedio-tpf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-java-intermedio-tpf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-java-intermedio-tpf` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db-java-intermedio-tpf` ;

-- -----------------------------------------------------
-- Table `db-java-intermedio-tpf`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-java-intermedio-tpf`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db-java-intermedio-tpf`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-java-intermedio-tpf`.`cliente` (
  `dni` INT NOT NULL,
  `direcction` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db-java-intermedio-tpf`.`tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-java-intermedio-tpf`.`tecnico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db-java-intermedio-tpf`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-java-intermedio-tpf`.`orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `costo` DOUBLE NULL DEFAULT NULL,
  `estado` BIT(1) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_tecnico` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK12d5tlp8o1xan9iqtv8tg2soi` (`id_categoria` ASC) VISIBLE,
  INDEX `FK2q1npk79pf5vd9n5ot07drnb4` (`id_cliente` ASC) VISIBLE,
  INDEX `FKnysvyoklijfx0gkegq9tfrm09` (`id_tecnico` ASC) VISIBLE,
  CONSTRAINT `FK12d5tlp8o1xan9iqtv8tg2soi`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db-java-intermedio-tpf`.`categoria` (`id`),
  CONSTRAINT `FK2q1npk79pf5vd9n5ot07drnb4`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db-java-intermedio-tpf`.`cliente` (`dni`),
  CONSTRAINT `FKnysvyoklijfx0gkegq9tfrm09`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `db-java-intermedio-tpf`.`tecnico` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
